# Build sdist+wheel packages using GitHub Actions.  Mostly adopted
# from https://cibuildwheel.readthedocs.io/en/stable/setup/

name: Build Python packages

on:
  push:
    # Don't build on pushes to arbitrary branches
    branches:
    # Do build on pushes to any release tag
    tags:
      - "zfec-.*"
  release:
    types: [published, created, edited]

env:
  # Just make sure that Python can use zfec package
  CIBW_TEST_COMMAND: python -c "import zfec; print(zfec.__version__)"

  # Twisted isn't quite ready on Windows Python 3.9
  CIBW_SKIP: cp39-win*

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-latest, macos-11]

    steps:
      - uses: actions/checkout@v2
        name: Check out zfec sources

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.7'

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel==1.6.4

      - name: Install Visual C++ for Python 2.7
        if: runner.os == 'Windows'
        run: |
          choco install vcpython27 -f -y

      - name: Build wheels
        run: |
          python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v2
        name: Upload artifacts
        with:
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Check out zfec sources

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.7'

      - name: Build sdist
        run: python setup.py sdist

      - uses: actions/upload-artifact@v2
        name: Upload artifacts
        with:
          path: dist/*.tar.gz
